<?php


namespace App\Services;


use App\Models\UserBalanceHistory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserBalanceHistoryService extends AbstractBaseService
{
    private $userBalanceService;

    public function __construct(UserBalanceHistory $userBalanceHistory, UserBalanceService $userBalanceService)
    {
        $this->model = $userBalanceHistory;
        $this->userBalanceService = $userBalanceService;
    }

    public function getAll()
    {
        return $this->model->whereHas('userBalance', function ($query) {
            $query->where('user_id', Auth::user()->id);
        })->get();
    }

    public function create(Request $request)
    {
        $this->model->userBalance()->associate($this->userBalanceService->getById($request->get('user_balance_id')));
        return parent::create($request); // TODO: Change the autogenerated stub
    }

    public function update(Request $request, $id)
    {
        return parent::update($request, $id); // TODO: Change the autogenerated stub
    }
}
